./example_birds.sh bird/bird_imagenet/bird_3_1.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_2.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_3.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_4.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_5.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_6.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_7.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_8.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_9.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_10.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_11.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_12.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_13.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_14.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_15.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_16.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_17.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_3_18.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_6.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_7.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_8.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_9.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_10.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_11.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_12.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_13.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_14.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_15.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_16.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_17.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_18.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_19.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_5_20.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_6_1.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_6_2.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_6_3.jpg gan_output/sentence_1_11.jpg
./example_birds.sh bird/bird_imagenet/bird_6_4.jpg gan_output/sentence_1_11.jpg
