./example_flower.sh flower/flower_1_10.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_11.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_1.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_2.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_3.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_4.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_5.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_6.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_7.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_8.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_1_9.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_10.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_11.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_12.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_13.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_14.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_15.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_16.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_17.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_18.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_19.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_1.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_2.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_3.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_4.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_5.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_7.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_2_9.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_1.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_2.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_3.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_4.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_5.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_3_6.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_10.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_11.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_12.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_13.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_14.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_15.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_16.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_17.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_18.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_19.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_1.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_20.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_21.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_22.png gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_23.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_24.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_25.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_26.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_27.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_2.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_3.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_5.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_6.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_7.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_8.jpg gan_flowers/sentence_1_11.jpg
./example_flower.sh flower/flower_4_9.jpg gan_flowers/sentence_1_11.jpg
